# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       love

# >> macros
%define _binary_payload w2.xzdio
# << macros

Summary:    LÖVE is an awesome 2D game framework for Lua
Version:    11.3
Release:    0
Group:      Applications
License:    ASL 2.0
URL:        https://github.com/savegame/love/tree/sailfish
Source0:    %{name}-%{version}.tar.bz2
Source1:    Love2D.permission
Source101:  love-rpmlintrc
Requires:   lua
BuildRequires:  pkgconfig(freetype2)
BuildRequires:  pkgconfig(glesv2)
BuildRequires:  pkgconfig(lua)
BuildRequires:  pkgconfig(openal)
BuildRequires:  pkgconfig(sdl2)
BuildRequires:  pkgconfig(theora)
BuildRequires:  pkgconfig(vorbis)
BuildRequires:  pkgconfig(zlib)
BuildRequires:  pkgconfig(libmodplug)
BuildRequires:  mpg123-devel
BuildRequires:  desktop-file-utils

%description
%{summary}.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
ls -l
platform/unix/automagic
%configure --help
# << build pre

%configure --disable-static \
    --with-lua=lua

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
install -d %{buildroot}%{_datadir}/games/love
install -d %{buildroot}%{_sysconfdir}/sailjail/permissions/
install -m644 %SOURCE1 %{buildroot}%{_sysconfdir}/sailjail/permissions/
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}/*
%{_libdir}/*
%{_datadir}/applications/love.desktop
%{_datadir}/icons/hicolor/scalable/mimetypes/application-x-love-game.svg
%exclude %{_mandir}/man1/love.1.gz
%exclude %{_datadir}/mime/packages/love.xml
%exclude %{_datadir}/pixmaps/love.svg
%dir %{_datadir}/games/love
%config %{_sysconfdir}/sailjail/permissions/Love2D.permission
# >> files
# << files

